# Columns to drop during data cleaning
drop_cols: 
  - "pos_touches"
  - "Att Pen"
  - "id"

# Categorical columns used in the analysis
categorical_columns:
  - "element_type"
  - "web_name"
  - "team_name"
  - "opponent_team_name"
  - "was_home"
  - "gameweek"

# Numerical columns used in the analysis
numerical_columns:
  - "now_cost"
  - "selected_by_percent"
  - "shots"
  - "SoT"
  - "SiB"
  - "xG"
  - "npxG"
  - "G"
  - "npG"
  - "key_passes"
  - "xA"
  - "A"
  - "xGC"
  - "GC"
  - "xCS"
  - "CS"
  - "xGI"
  - "npxGI"
  - "xP"
  - "PvsxP"
  - "carries_final_third"
  - "carries_penalty_area"
  - "minutes"

# Target column for model training
target_column: 
  - "total_points"

# API Configuration (Ensure the API key is handled securely)
api_config:
  url: "https://api.football-data.org/v4/competitions/PL/matches"
  api_key: "your_api_key_here"  # Replace with a secure method to handle the API key

# Mapping of team names from the API to standardized names
team_name_mapping: 
  Arsenal FC: "Arsenal"
  Fulham FC: "Fulham"
  Aston Villa FC: "Aston Villa"
  Southampton FC: "Southampton"
  AFC Bournemouth: "Bournemouth"
  Tottenham Hotspur FC: "Tottenham"
  Brentford FC: "Brentford"
  Brighton & Hove Albion FC: "Brighton"
  Leicester City FC: "Leicester"
  Chelsea FC: "Chelsea"
  Crystal Palace FC: "Crystal Palace"
  Everton FC: "Everton"
  Ipswich Town FC: "Ipswich"
  Liverpool FC: "Liverpool"
  Manchester City FC: "Manchester City"
  Manchester United FC: "Manchester United"
  West Ham United FC: "West Ham"
  Newcastle United FC: "Newcastle United"
  Nottingham Forest FC: "Nottingham Forest"
  Wolverhampton Wanderers FC: "Wolverhampton Wanderers"

# Columns for inference
inference_columns: 
  - "element_type"
  - "web_name"
  - "team_name"
  - "opponent_team_name"
  - "was_home"
  - "gameweek"  
  - "now_cost"
  - "total_points"

# Model Information
models:
  linear_regression:
    version: "v1.0"
    last_trained: "September 5, 2024"
    path: "models/linear_regression.pkl"
  
  xgboost:
    version: "v1.0"
    last_trained: "September 5, 2024"
    path: "models/xgboost_model.pkl"
  
  preprocessing_pipeline:
    version: "v1.0"
    last_trained: "September 5, 2024"
    path: "models/processor.pkl"